# Generated by Django 3.2.25 on 2025-04-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='allData',
            fields=[
                ('Name', models.CharField(max_length=50, null=True)),
                ('count', models.AutoField(primary_key=True, serialize=False)),
                ('commend', models.TextField(null=True)),
            ],
        ),
    ]
