# Generated by Django 3.2.25 on 2025-04-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alldata',
            name='avg',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='alldata',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='alldata',
            name='during',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='alldata',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='alldata',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='alldata',
            name='set',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='alldata',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
