# Generated by Django 3.2.25 on 2025-04-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20250404_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alldata',
            name='number',
            field=models.BigIntegerField(null=True),
        ),
    ]
