# Generated by Django 3.2.25 on 2025-04-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_alter_alldata_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('orderQty', models.IntegerField(null=True)),
                ('sellQty', models.IntegerField(null=True)),
            ],
        ),
    ]
